### ISSUE TITLE
How do I create unit testing on laminas-api-tools ?

### ISSUE THREAD

**Issue by jplt001** [laminas-api-tools/api-tools#79]

**Comment by samsonasik** [comment]
laminas-api-tools is using laminas mvc, you can read the docs for unit testing https://docs.laminas.dev/tutorials/unit-testing/

**Comment by karthikeyan-manivasagam** [comment]
How to write tests for resource which extend this classes Laminas\ApiTools\Rest\AbstractResourceListener, I dont think the official documentation have anything related to this
