### ISSUE TITLE
php public/index.php returns base path error

### ISSUE THREAD

**Issue by adarshkhatri** [laminas-api-tools/api-tools#82]
#### Summary

When I run `php public/index.php` it returns this error:

> Uncaught Laminas\View\Exception\RuntimeException: No base path provided in vendor\laminas\laminas-view\src\Helper\BasePath.php:37

However, running `php public/index.php development enable` does work.

I have updated `laminas-view` and `laminas-cache` to the latest version but no help.

Is this normal behavior?

#### Current behavior
Throws error. `Uncaught Laminas\View\Exception\RuntimeException: No base path provided in vendor\laminas\laminas-view\src\Helper\BasePath.php:37`

#### How to reproduce
Run `php public/index.php`

#### Expected behavior
Show the command line tools.

**Comment by samsonasik** [comment]
This component mostly used via api-tools-skeleton, please follow documentation at https://api-tools.getlaminas.org/documentation/intro/installation .

If the issue persist, please re-create issue at https://github.com/laminas-api-tools/api-tools-skeleton
